### ISSUE TITLE
Struggling to install, not sure where to go!

### ISSUE THREAD

**Issue by pwarren** [titanous/homebrew-gnuradio#15]
Probably a PEBKAC, but, I'm going through your instructions, and keep failing on the scipy installation, it appears to not be able to detect the numpy installation.

``` sh
Hollis:~ pwarren$ /usr/local/share/python/pip install https://github.com/scipy/scipy/tarball/v0.11.0rc2
Downloading/unpacking https://github.com/scipy/scipy/tarball/v0.11.0rc2
  Downloading v0.11.0rc2 (9.9MB): 9.9MB downloaded
  Running setup.py egg_info for package from https://github.com/scipy/scipy/tarball/v0.11.0rc2
    blas_opt_info:
      FOUND:
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3)]
        extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']

    lapack_opt_info:
      FOUND:
        extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
        define_macros = [('NO_ATLAS_INFO', 3)]
        extra_compile_args = ['-msse3']

    umfpack_info:
      libraries umfpack not found in /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib
    amd_info:
      libraries amd not found in /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib
      FOUND:
        libraries = ['amd']
        library_dirs = ['/usr/local/lib']
        swig_opts = ['-I/usr/local/include']
        define_macros = [('SCIPY_AMD_H', None)]
        include_dirs = ['/usr/local/include']

      FOUND:
        libraries = ['umfpack', 'amd']
        library_dirs = ['/usr/local/lib']
        swig_opts = ['-I/usr/local/include', '-I/usr/local/include']
        define_macros = [('SCIPY_UMFPACK_H', None), ('SCIPY_AMD_H', None)]
        include_dirs = ['/usr/local/include']

    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 208, in <module>
        setup_package()
      File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 199, in setup_package
        configuration=configuration )
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 152, in setup
        config = configuration()
      File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 136, in configuration
        config.add_subpackage('scipy')
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 19, in configuration
        config.add_subpackage('special')
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "/private/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/scipy/special/setup.py", line 54, in configuration
        extra_info=get_info("npymath")
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 2220, in get_info
        pkg_info = get_pkg_info(pkgname, dirs)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 2172, in get_pkg_info
        return read_config(pkgname, dirs)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 390, in read_config
        v = _read_config_imp(pkg_to_filename(pkgname), dirs)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 326, in _read_config_imp
        meta, vars, sections, reqs = _read_config(filenames)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 309, in _read_config
        meta, vars, sections, reqs = parse_config(f, dirs)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 281, in parse_config
        raise PkgNotFound("Could not find file(s) %s" % str(filenames))
    numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/usr/local/lib/python2.7/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']
    Complete output from command python setup.py egg_info:
    blas_opt_info:

  FOUND:

    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']

    define_macros = [('NO_ATLAS_INFO', 3)]

    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']



lapack_opt_info:

  FOUND:

    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']

    define_macros = [('NO_ATLAS_INFO', 3)]

    extra_compile_args = ['-msse3']



umfpack_info:

  libraries umfpack not found in /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib

amd_info:

  libraries amd not found in /usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib

  FOUND:

    libraries = ['amd']

    library_dirs = ['/usr/local/lib']

    swig_opts = ['-I/usr/local/include']

    define_macros = [('SCIPY_AMD_H', None)]

    include_dirs = ['/usr/local/include']



  FOUND:

    libraries = ['umfpack', 'amd']

    library_dirs = ['/usr/local/lib']

    swig_opts = ['-I/usr/local/include', '-I/usr/local/include']

    define_macros = [('SCIPY_UMFPACK_H', None), ('SCIPY_AMD_H', None)]

    include_dirs = ['/usr/local/include']



Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 208, in <module>

    setup_package()

  File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 199, in setup_package

    configuration=configuration )

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 152, in setup

    config = configuration()

  File "/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/setup.py", line 136, in configuration

    config.add_subpackage('scipy')

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage

    caller_level = 2)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "scipy/setup.py", line 19, in configuration

    config.add_subpackage('special')

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage

    caller_level = 2)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage

    caller_level = caller_level + 1)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py

    config = setup_module.configuration(*args)

  File "/private/var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build/scipy/special/setup.py", line 54, in configuration

    extra_info=get_info("npymath")

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 2220, in get_info

    pkg_info = get_pkg_info(pkgname, dirs)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 2172, in get_pkg_info

    return read_config(pkgname, dirs)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 390, in read_config

    v = _read_config_imp(pkg_to_filename(pkgname), dirs)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 326, in _read_config_imp

    meta, vars, sections, reqs = _read_config(filenames)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 309, in _read_config

    meta, vars, sections, reqs = parse_config(f, dirs)

  File "/usr/local/lib/python2.7/site-packages/numpy/distutils/npy_pkg_config.py", line 281, in parse_config

    raise PkgNotFound("Could not find file(s) %s" % str(filenames))

numpy.distutils.npy_pkg_config.PkgNotFound: Could not find file(s) ['/usr/local/lib/python2.7/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini']

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /var/folders/rj/7k9g5zdd705cjxmc1f2hl0j00000gn/T/pip-CUD6uJ-build
Storing complete log in /Users/pwarren/.pip/pip.log
```

the /usr/local/lib/python2.7/site-packages/numpy/core/lib/npy-pkg-config/npymath.ini'

Does not seem to exist, but there are a bunch of python files in /usr/local/lib/python2.7/site-packages/numpy/core/

I'm using a brand new macbook air 13", with OS X 10.8.1 and xcode 4.4.1, I did the homebrew install, and hombrew doctor, and homebrew install wget worked pretty well ;)

Just a bit lost with all this, thanks for any help!

**Comment by pwarren** [comment]
``` sh
Hollis:~ pwarren$ echo $PATH
/usr/local/bin:/usr/local/share/python:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
Hollis:~ pwarren$ echo $PYTHONPATH
/usr/local/lib/python2.7/site-packages/:/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/:
Hollis:~ pwarren$ 
```

Some more info

**Comment by dweeks** [comment]
I too ran into the missing 

npymath.ini

file problem on a 10.7.4 machine.  The solution for me was to install numpy from source.

**Comment by pwarren** [comment]
Yep, downloading from sourceforge, 

``` sh
python setup.py build
python setup.py install
```

and we're all good.

**Comment by pwarren** [comment]
Well, not quite all good.

Now it's complaining: No available formula for gnuradio

``` sh
pc-00201:~ pwarren$ brew install gnuradio
Error: No available formula for gnuradio 
pc-00201:~ pwarren$ brew tap titanous/homebrew-gnuradio
Error: Already tapped!
```

sad face!

**Comment by dweeks** [comment]
That is strange - I did not run into that problem.

How about trying:

brew uninstall gnuradio
brew untap titanous/homebrew-gnuradio
brew tap titanous/homebrew-gnuradio
brew tap --repair
brew install gnuradio

**Comment by pwarren** [comment]
the brew untap then retap seemed to do the trick.

THanks for the help dweeks. This has been the first time I've tried homebrew, think I'm starting to like it :)

**Comment by lokkju** [comment]
per https://github.com/pypa/pip/issues/707, try this:

```
brew tap samueljohn/python
brew install numpy
brew install scipy
```
