### ISSUE TITLE
installing gnuradio on 10.10.1

### ISSUE THREAD

**Issue by mmonka** [titanous/homebrew-gnuradio#55]
i try to install gnuradio on my mac (10.10.1)

> gcc -v
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
> Target: x86_64-apple-darwin14.0.0
> Thread model: posix

$ brew install gnuradio
==> Installing gnuradio from titanous/homebrew-gnuradio
==> Downloading http://gnuradio.org/releases/gnuradio/gnuradio-3.6.5.1.tar.gz
###### ################################################################## 100,0%

==> Patching
patching file grc/CMakeLists.txt
patching file gr-qtgui/lib/spectrumdisplayform.ui
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.5.1 -DQWT_INCLUDE_DIRS=/usr/local/lib/qwt.framework/Headers -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnuradio/3.6.5.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DENABLE_GR_QTGUI=OFF -DENABLE_DOXYGEN=OFF 
==> make
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: ld returned 1 exit status
make[2]: **\* [volk/lib/libvolk.0.0.0.dylib] Error 1
make[1]: **\* [volk/lib/CMakeFiles/volk.dir/all] Error 2
make: **\* [all] Error 2
couldn't understand kern.osversion `14.0.0'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/titanous/homebrew-gnuradio/issues

Any idea how to solve this? Do you need more details for debugging?

**Comment by freelancer77** [comment]
I second that.

**Comment by Oxtay** [comment]
You might've already tried this, but according to [this link](http://stackoverflow.com/questions/26486163/gcc-4-9-1-in-os-x-yosemite-gcc-warning-couldn-t-understand-kern-osversion-1), the solution might be to upgrate `gcc`:

`brew upgrade gcc`

**Comment by wyager** [comment]
Same here(?). Upgrading gcc did not help. I also upgraded to 10.10.2, and the message changed from 

```
couldn't understand kern.osversion `14.0.0'
```

 to 

```
couldn't understand kern.osversion `14.1.0'
```

Here's the whole output, in case it's actually something else:

```
==> Installing gnuradio from titanous/homebrew-gnuradio
==> Downloading http://gnuradio.org/releases/gnuradio/gnuradio-3.6.5.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/gnuradio-3.6.5.1.tar.gz
==> Patching
patching file grc/CMakeLists.txt
patching file gr-qtgui/lib/spectrumdisplayform.ui
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.5.1 -DQWT_INCLUD
==> make
4 errors generated.
make[2]: *** [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/ppio_ppdev.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/all] Error 2
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'
```

**Comment by galgolan** [comment]
Im also having the same issue:
Gals-MacBook-Air:~ galgo$ brew install gnuradio --with-qt
==> Installing gnuradio from titanous/homebrew-gnuradio
==> Downloading http://gnuradio.org/releases/gnuradio/gnuradio-3.6.5.1.tar.gz
Already downloaded: /Library/Caches/Homebrew/gnuradio-3.6.5.1.tar.gz
==> Patching
patching file grc/CMakeLists.txt
patching file gr-qtgui/lib/spectrumdisplayform.ui
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.5.1 -DQWT_INCLUD
==> make
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: ld returned 1 exit status
make[2]: **\* [volk/lib/libvolk.0.0.0.dylib] Error 1
make[1]: **\* [volk/lib/CMakeFiles/volk.dir/all] Error 2
make: **\* [all] Error 2
couldn't understand kern.osversion `14.1.0'
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

**Comment by miaoski** [comment]
Same thing here

```
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.5.1 -DQWT_INCLUDE_DIRS=/usr/local/lib/qwt.framework/Headers -DCMAKE_IN
==> make
make[2]: *** [volk/lib/CMakeFiles/volk.dir/volk_16i_s32f_deinterleave_32f_x2_a_orc_impl.c.o] Error 1
make[2]: *** [volk/lib/CMakeFiles/volk.dir/volk_16ic_deinterleave_real_8i_a_orc_impl.c.o] Error 1
make[2]: *** [volk/lib/CMakeFiles/volk.dir/volk_16ic_magnitude_16i_a_orc_impl.c.o] Error 1
make[1]: *** [volk/lib/CMakeFiles/volk.dir/all] Error 2
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'
```

**Comment by propellerhat** [comment]
I, too, have this issue.

Firstly, I installed apple-gcc42 because it was listed as a dependency:

```
brew install --with-qt gnuradio
==> Installing gnuradio from titanous/homebrew-gnuradio
Error: No available formula for apple-gcc42 (dependency of gnuradio)
Searching formulae...
Searching taps...
homebrew/dupes/apple-gcc42
```

So I installed apple-gcc42 like it wanted:

```
brew install homebrew/dupes/apple-gcc42
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-dupes'...
remote: Counting objects: 1581, done.
...
```

Then the installation of gnuradio proceeded until I had the same error as mmonka:

```
brew install --with-qt gnuradio
==> Installing gnuradio from titanous/homebrew-gnuradio 
...
<Several lines omitted>
...
==> Installing gnuradio
==> Downloading http://gnuradio.org/releases/gnuradio/gnuradio-3.6.5.1.tar.gz
######################################################################## 100.0%
==> Patching
patching file grc/CMakeLists.txt
patching file gr-qtgui/lib/spectrumdisplayform.ui
==> cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/gnuradio/3.6.5.1 -DQWT_INCLUDE_DIRS=/usr/local/lib/qwt.framework/Headers -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/gnuradio/3.6.5.1 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_V
==> make
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: ld returned 1 exit status
make[2]: *** [volk/lib/libvolk.0.0.0.dylib] Error 1
make[1]: *** [volk/lib/CMakeFiles/volk.dir/all] Error 2
make: *** [all] Error 2
couldn't understand kern.osversion `14.1.0'

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/titanous/homebrew-gnuradio/issues
```

This seems to be an error generated by the version of gcc it wanted. If I run the apple-gcc42 that was installed, I get the same error:

```
gcc-4.2
couldn't understand kern.osversion `14.1.0'
i686-apple-darwin11-gcc-4.2.1: no input files
```

Lines 49-51 in gnuradio.rb force compilation with gcc-4.2. I'm going to attempt to change that to gcc-4.9 and see if it works. I'll report back soon...

# Edit

Okay, I removed the gcc-4.2 requirement. The error:

```
couldn't understand kern.osversion `14.1.0'
```

is not present anymore, but the build blows up nonetheless. Here's what I'm getting now (running brew with the -vd flags):

```
In file included from /tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.cc:26:
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.h:38:38: error: friend declaration specifying a default argument must be a definition
  friend GR_CORE_API ppio_ppdev_sptr make_ppio_ppdev (int which = 0);
                                     ^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.h:58:1: error: friend declaration specifying a default argument must be the only declaration
make_ppio_ppdev (int which);
^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.h:38:38: note: previous declaration is here
  friend GR_CORE_API ppio_ppdev_sptr make_ppio_ppdev (int which = 0);
                                     ^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.cc:318:1: error: friend declaration specifying a default argument must be the only declaration
make_ppio_ppdev (int which)
^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.h:38:38: note: previous declaration is here
  friend GR_CORE_API ppio_ppdev_sptr make_ppio_ppdev (int which = 0);
                                 ^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.cc:320:31: error: calling a private constructor of class 'ppio_ppdev'
  return ppio_ppdev_sptr (new ppio_ppdev (which));
                              ^
/tmp/gnuradio-RMWYXw/gnuradio-3.6.5.1/gnuradio-core/src/lib/io/ppio_ppdev.h:39:3: note: implicitly declared private here
  ppio_ppdev (int which = 0);
  ^
4 errors generated.
make[2]: *** [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/io/ppio_ppdev.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [gnuradio-core/src/lib/CMakeFiles/gnuradio-core.dir/all] Error 2
make: *** [all] Error 2
```

Going to update shortly once I try to fix this...

# Edit 2

I tried using clang and gcc-4.9. Neither worked. I gave up and just used robotastic/hackrf/gnuradio, since that one actually works.

**Comment by vampjaz** [comment]
Any news? I have this problem too...
I tried uninstalling macports as suggested, and it broke the funcionality of `ld`, but I fixed that by setting MACOSX_DEPLOYMENT_TARGET=10.9. The error came back.

**Comment by andrewmoskal** [comment]
brew install -vd --with-qt gnuradio
...
[  6%] Linking C shared library libvolk.dylib
cd /tmp/gnuradio20150828-91942-op236z/gnuradio-3.6.5.1/build/volk/lib && /usr/local/Cellar/cmake/3.3.1/bin/cmake -E cmake_link_script CMakeFiles/volk.dir/link.txt --verbose=1
/usr/local/bin/gcc-4.2   -dynamiclib -Wl,-headerpad_max_install_names  -o libvolk.0.0.0.dylib -install_name /tmp/gnuradio20150828-91942-op236z/gnuradio-3.6.5.1/build/volk/lib/libvolk.0.0.0.dylib CMakeFiles/volk.dir/volk_16i_s32f_deinterleave_32f_x2_a_orc_impl.c.o CMakeFiles/volk.dir/volk_16ic_deinterleave_16i_x2_a_orc_impl.c.o CMakeFiles/volk.dir/volk_16ic_deinterleave_real_8i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_16ic_magnitude_16i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_16sc_magnitude_32f_aligned16_orc_impl.c.o CMakeFiles/volk.dir/volk_16u_byteswap_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_s32f_multiply_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_s32f_normalize_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_sqrt_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_add_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_divide_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_dot_prod_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_max_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_min_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_multiply_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32f_x2_subtract_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32fc_32f_multiply_32fc_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32fc_magnitude_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32fc_s32f_magnitude_16i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32fc_s32fc_multiply_32fc_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32fc_x2_multiply_32fc_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32i_x2_and_32i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_32i_x2_or_32i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_8i_convert_16i_a_orc_impl.c.o CMakeFiles/volk.dir/volk_8i_s32f_convert_32f_a_orc_impl.c.o CMakeFiles/volk.dir/volk_prefs.c.o CMakeFiles/volk.dir/volk_rank_archs.c.o CMakeFiles/volk.dir/volk.c.o CMakeFiles/volk.dir/volk_cpu.c.o CMakeFiles/volk.dir/volk_machines.c.o CMakeFiles/volk.dir/volk_machine_generic_orc.c.o CMakeFiles/volk.dir/volk_machine_sse2_64_mmx_orc.c.o CMakeFiles/volk.dir/volk_machine_sse3_64_orc.c.o CMakeFiles/volk.dir/volk_machine_ssse3_64_orc.c.o CMakeFiles/volk.dir/volk_machine_sse4_1_64_orc.c.o  -L/usr/local/Cellar/orc/0.4.23/lib /usr/local/lib/liborc-0.4.dylib -Wl,-rpath,/usr/local/Cellar/orc/0.4.23/lib 
couldn't understand kern.osversion `14.5.0'
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: ld returned 1 exit status
make[2]: *** [volk/lib/libvolk.0.0.0.dylib] Error 1
make[1]: *** [volk/lib/CMakeFiles/volk.dir/all] Error 2
make: *** [all] Error 2
couldn't understand kern.osversion`14.5.0'
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'

**Comment by andrewmoskal** [comment]
brew install -vd --with-qt gnuradio

**Comment by andrewmoskal** [comment]
In case HEAD version:

Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 22e2f1a cmake: update revision to 3.7.8 for feature release
git submodule foreach --recursive git submodule sync
Entering 'volk'
git submodule update --init --recursive
==> Checking out branch master
==> Patching
patching file grc/CMakeLists.txt
patching file gr-qtgui/lib/spectrumdisplayform.ui
Hunk #1 FAILED at 518.
1 out of 1 hunk FAILED -- saving rejects to file gr-qtgui/lib/spectrumdisplayform.ui.rej
/usr/local/Library/Homebrew/debrew.rb:11:in `raise'
ErrorDuringExecution: Failure while executing: /usr/bin/patch -g 0 -f -p1
